---
- hosts: local
  connection: local
  roles:
    - bootstrap
    - jquery
    - zuul
  vars:
    jquery_visibility_yui_install_location: '/var/lib/zuul/www/jquery-visibility.min.js'
    checkouts: '/var/checkouts'
