---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: make zuul directories
  file: path={{ zuul_venv }} owner={{ zuul_user }} group={{ zuul_group }} mode=0755 state=directory
  file: path={{ zuul_app }} owner={{ zuul_user }} group={{ zuul_group }} mode=0755 state=directory

- name: install pip requirements.
  pip: requirements={{ zuul_app }}/requirements.txt virtualenv={{ zuul_venv }}

